// Mock in-memory database initialized from enterprise seed data for GitHub Pages Live Preview

export const initialUsers = [
  { user_id: 1, employee_code: 'EMP001', full_name: 'Sarah Jenkins', email: 'sarah.jenkins@company.com', phone: '+1-555-0101', role: 'CFO', department_id: 5, department_name: 'Finance, Legal & Compliance', department_code: 'FIN', manager_id: null, manager_name: null, is_active: 1 },
  { user_id: 2, employee_code: 'EMP002', full_name: 'David Miller', email: 'david.miller@company.com', phone: '+1-555-0102', role: 'FINANCE_ADMIN', department_id: 5, department_name: 'Finance, Legal & Compliance', department_code: 'FIN', manager_id: 1, manager_name: 'Sarah Jenkins', is_active: 1 },
  { user_id: 3, employee_code: 'EMP003', full_name: 'Victoria Sterling', email: 'victoria.s@company.com', phone: '+1-555-0103', role: 'AUDITOR', department_id: 5, department_name: 'Finance, Legal & Compliance', department_code: 'FIN', manager_id: 1, manager_name: 'Sarah Jenkins', is_active: 1 },
  { user_id: 4, employee_code: 'EMP010', full_name: 'Alex Chen', email: 'alex.chen@company.com', phone: '+1-555-0201', role: 'DEPARTMENT_HEAD', department_id: 1, department_name: 'Engineering & Product', department_code: 'ENG', manager_id: 1, manager_name: 'Sarah Jenkins', is_active: 1 },
  { user_id: 5, employee_code: 'EMP011', full_name: 'Elena Rostova', email: 'elena.rostova@company.com', phone: '+1-555-0202', role: 'MANAGER', department_id: 2, department_name: 'Marketing & Growth', department_code: 'MKT', manager_id: 1, manager_name: 'Sarah Jenkins', is_active: 1 },
  { user_id: 6, employee_code: 'EMP012', full_name: 'Marcus Brody', email: 'marcus.brody@company.com', phone: '+1-555-0203', role: 'MANAGER', department_id: 3, department_name: 'Sales & Enterprise Accounts', department_code: 'SLS', manager_id: 1, manager_name: 'Sarah Jenkins', is_active: 1 },
  { user_id: 7, employee_code: 'EMP013', full_name: 'Rachel Green', email: 'rachel.green@company.com', phone: '+1-555-0204', role: 'MANAGER', department_id: 4, department_name: 'People & Talent Operations', department_code: 'HR', manager_id: 1, manager_name: 'Sarah Jenkins', is_active: 1 },
  { user_id: 8, employee_code: 'EMP014', full_name: 'Carlos Mendez', email: 'carlos.m@company.com', phone: '+1-555-0205', role: 'MANAGER', department_id: 6, department_name: 'Customer Operations & Support', department_code: 'OPS', manager_id: 1, manager_name: 'Sarah Jenkins', is_active: 1 },
  { user_id: 9, employee_code: 'EMP101', full_name: 'Liam Vance', email: 'liam.vance@company.com', phone: '+1-555-0301', role: 'EMPLOYEE', department_id: 1, department_name: 'Engineering & Product', department_code: 'ENG', manager_id: 4, manager_name: 'Alex Chen', is_active: 1 },
  { user_id: 10, employee_code: 'EMP102', full_name: 'Chloe Zhao', email: 'chloe.zhao@company.com', phone: '+1-555-0302', role: 'EMPLOYEE', department_id: 1, department_name: 'Engineering & Product', department_code: 'ENG', manager_id: 4, manager_name: 'Alex Chen', is_active: 1 },
  { user_id: 11, employee_code: 'EMP103', full_name: 'Noah Patel', email: 'noah.patel@company.com', phone: '+1-555-0303', role: 'EMPLOYEE', department_id: 2, department_name: 'Marketing & Growth', department_code: 'MKT', manager_id: 5, manager_name: 'Elena Rostova', is_active: 1 },
  { user_id: 12, employee_code: 'EMP104', full_name: 'Sophia Taylor', email: 'sophia.taylor@company.com', phone: '+1-555-0304', role: 'EMPLOYEE', department_id: 3, department_name: 'Sales & Enterprise Accounts', department_code: 'SLS', manager_id: 6, manager_name: 'Marcus Brody', is_active: 1 },
  { user_id: 13, employee_code: 'EMP105', full_name: 'Jordan Lee', email: 'jordan.lee@company.com', phone: '+1-555-0305', role: 'EMPLOYEE', department_id: 4, department_name: 'People & Talent Operations', department_code: 'HR', manager_id: 7, manager_name: 'Rachel Green', is_active: 1 },
  { user_id: 14, employee_code: 'EMP106', full_name: 'Aiden Walker', email: 'aiden.walker@company.com', phone: '+1-555-0306', role: 'EMPLOYEE', department_id: 6, department_name: 'Customer Operations & Support', department_code: 'OPS', manager_id: 8, manager_name: 'Carlos Mendez', is_active: 1 }
];

export const initialDepartments = [
  { department_id: 1, department_code: 'ENG', name: 'Engineering & Product', description: 'Software development, cloud infrastructure, QA, and platform architecture', high_value_threshold: 2500.00, manager_id: 4, manager_name: 'Alex Chen', budget_id: 1, allocated_amount: 120000.00, spent_amount: 54200.00, reserved_amount: 8300.00, remaining_funds: 57500.00 },
  { department_id: 2, department_code: 'MKT', name: 'Marketing & Growth', description: 'Brand marketing, digital advertising, conferences, content creation, and PR', high_value_threshold: 1500.00, manager_id: 5, manager_name: 'Elena Rostova', budget_id: 2, allocated_amount: 75000.00, spent_amount: 58400.00, reserved_amount: 7000.00, remaining_funds: 9600.00 },
  { department_id: 3, department_code: 'SLS', name: 'Sales & Enterprise Accounts', description: 'Client meetings, enterprise demos, sales travel, customer entertainment', high_value_threshold: 1200.00, manager_id: 6, manager_name: 'Marcus Brody', budget_id: 3, allocated_amount: 60000.00, spent_amount: 52100.00, reserved_amount: 6000.00, remaining_funds: 1900.00 },
  { department_id: 4, department_code: 'HR', name: 'People & Talent Operations', description: 'Recruiting, employee wellness, training programs, HR software', high_value_threshold: 800.00, manager_id: 7, manager_name: 'Rachel Green', budget_id: 4, allocated_amount: 30000.00, spent_amount: 11500.00, reserved_amount: 1550.00, remaining_funds: 16950.00 },
  { department_id: 5, department_code: 'FIN', name: 'Finance, Legal & Compliance', description: 'Treasury, compliance, tax, audits, insurance, and executive operations', high_value_threshold: 3000.00, manager_id: 1, manager_name: 'Sarah Jenkins', budget_id: 5, allocated_amount: 40000.00, spent_amount: 14200.00, reserved_amount: 1300.00, remaining_funds: 24500.00 },
  { department_id: 6, department_code: 'OPS', name: 'Customer Operations & Support', description: 'Customer success, support tooling, logistics, call center operations', high_value_threshold: 1000.00, manager_id: 8, manager_name: 'Carlos Mendez', budget_id: 6, allocated_amount: 35000.00, spent_amount: 26800.00, reserved_amount: 2350.00, remaining_funds: 5850.00 }
];

export const initialCategories = [
  { category_id: 1, code: 'TRV-AIR', category_name: 'Airfare & Flights', description: 'Domestic and international business flight bookings', gl_account_code: 'GL-6100', requires_receipt: 1, max_single_item_limit: 5000.00, requires_executive_approval: 1 },
  { category_id: 2, code: 'TRV-LOD', category_name: 'Lodging & Hotels', description: 'Hotel accommodations for corporate business travel', gl_account_code: 'GL-6110', requires_receipt: 1, max_single_item_limit: 1500.00, requires_executive_approval: 0 },
  { category_id: 3, code: 'TRV-TRN', category_name: 'Ground Transportation', description: 'Rental cars, taxis, Uber/Lyft, train fares, and toll road charges', gl_account_code: 'GL-6120', requires_receipt: 1, max_single_item_limit: 300.00, requires_executive_approval: 0 },
  { category_id: 4, code: 'MEL-ENT', category_name: 'Client Meals & Entertainment', description: 'Business dinners, client meetings, partner dinners', gl_account_code: 'GL-6200', requires_receipt: 1, max_single_item_limit: 500.00, requires_executive_approval: 0 },
  { category_id: 5, code: 'IT-CLD', category_name: 'Cloud & SaaS Subscriptions', description: 'AWS, GCP, Azure hosting, SaaS tools, productivity licenses', gl_account_code: 'GL-6300', requires_receipt: 1, max_single_item_limit: 10000.00, requires_executive_approval: 1 },
  { category_id: 6, code: 'IT-EQP', category_name: 'Hardware & Workstation Gear', description: 'Laptops, monitors, developer peripherals, ergonomic accessories', gl_account_code: 'GL-6310', requires_receipt: 1, max_single_item_limit: 3000.00, requires_executive_approval: 1 },
  { category_id: 7, code: 'EDU-CNF', category_name: 'Conferences & Certifications', description: 'Industry conference tickets, training seminars, skill certifications', gl_account_code: 'GL-6400', requires_receipt: 1, max_single_item_limit: 2000.00, requires_executive_approval: 0 },
  { category_id: 8, code: 'OFC-SPL', category_name: 'Office Supplies & Logistics', description: 'Stationery, shipping charges, office refreshments, team printing', gl_account_code: 'GL-6500', requires_receipt: 0, max_single_item_limit: 250.00, requires_executive_approval: 0 }
];

export const initialDepartmentBudgets = [
  { budget_id: 1, department_id: 1, department_code: 'ENG', department_name: 'Engineering & Product', fiscal_year: 2026, quarter: 3, allocated_amount: 120000.00, spent_amount: 54200.00, reserved_amount: 8300.00, total_committed: 62500.00, available_headroom: 57500.00, utilization_pct: 52.08, warning_threshold_pct: 80.00, critical_threshold_pct: 95.00, budget_health_status: 'HEALTHY' },
  { budget_id: 2, department_id: 2, department_code: 'MKT', department_name: 'Marketing & Growth', fiscal_year: 2026, quarter: 3, allocated_amount: 75000.00, spent_amount: 58400.00, reserved_amount: 7000.00, total_committed: 65400.00, available_headroom: 9600.00, utilization_pct: 87.20, warning_threshold_pct: 80.00, critical_threshold_pct: 95.00, budget_health_status: 'WARNING' },
  { budget_id: 3, department_id: 3, department_code: 'SLS', department_name: 'Sales & Enterprise Accounts', fiscal_year: 2026, quarter: 3, allocated_amount: 60000.00, spent_amount: 52100.00, reserved_amount: 6000.00, total_committed: 58100.00, available_headroom: 1900.00, utilization_pct: 96.83, warning_threshold_pct: 80.00, critical_threshold_pct: 95.00, budget_health_status: 'CRITICAL' },
  { budget_id: 4, department_id: 4, department_code: 'HR', department_name: 'People & Talent Operations', fiscal_year: 2026, quarter: 3, allocated_amount: 30000.00, spent_amount: 11500.00, reserved_amount: 1550.00, total_committed: 13050.00, available_headroom: 16950.00, utilization_pct: 43.50, warning_threshold_pct: 80.00, critical_threshold_pct: 95.00, budget_health_status: 'HEALTHY' },
  { budget_id: 5, department_id: 5, department_code: 'FIN', department_name: 'Finance, Legal & Compliance', fiscal_year: 2026, quarter: 3, allocated_amount: 40000.00, spent_amount: 14200.00, reserved_amount: 1300.00, total_committed: 15500.00, available_headroom: 24500.00, utilization_pct: 38.75, warning_threshold_pct: 80.00, critical_threshold_pct: 95.00, budget_health_status: 'HEALTHY' },
  { budget_id: 6, department_id: 6, department_code: 'OPS', department_name: 'Customer Operations & Support', fiscal_year: 2026, quarter: 3, allocated_amount: 35000.00, spent_amount: 26800.00, reserved_amount: 2350.00, total_committed: 29150.00, available_headroom: 5850.00, utilization_pct: 83.29, warning_threshold_pct: 80.00, critical_threshold_pct: 95.00, budget_health_status: 'WARNING' }
];

export const initialClaims = [
  { claim_id: 1, claim_number: 'EXP-2026-001', employee_id: 9, employee_name: 'Liam Vance', employee_code: 'EMP101', employee_email: 'liam.vance@company.com', department_id: 1, department_name: 'Engineering & Product', department_code: 'ENG', budget_id: 1, title: 'AWS Annual Cloud Reserved Instances Renewal', total_amount: 4850.00, currency: 'USD', status: 'APPROVED', is_high_value: 1, high_value_threshold: 2500.00, high_value_reason: 'Amount ($4,850.00) exceeds department threshold of $2,500.00', business_justification: '1-year upfront commitment for primary PostgreSQL and Kubernetes cluster saving 38% annual cloud costs.', submission_date: '2026-08-01 10:30:00', approved_at: '2026-08-03 14:00:00', reimbursed_at: '2026-08-05 16:30:00', item_count: 1 },
  { claim_id: 2, claim_number: 'EXP-2026-002', employee_id: 10, employee_name: 'Chloe Zhao', employee_code: 'EMP102', employee_email: 'chloe.zhao@company.com', department_id: 1, department_name: 'Engineering & Product', department_code: 'ENG', budget_id: 1, title: 'Development Dual 4K Monitor Setup & Docking Station', total_amount: 840.00, currency: 'USD', status: 'APPROVED', is_high_value: 0, high_value_threshold: 2500.00, high_value_reason: null, business_justification: 'Standard ergonomic equipment upgrade for remote engineering productivity.', submission_date: '2026-08-10 11:15:00', approved_at: '2026-08-11 09:20:00', reimbursed_at: '2026-08-15 12:00:00', item_count: 2 },
  { claim_id: 3, claim_number: 'EXP-2026-003', employee_id: 11, employee_name: 'Noah Patel', employee_code: 'EMP103', employee_email: 'noah.patel@company.com', department_id: 2, department_name: 'Marketing & Growth', department_code: 'MKT', budget_id: 2, title: 'HubSpot Enterprise Marketing Suite Annual Seat', total_amount: 3450.00, currency: 'USD', status: 'PENDING_FINANCE', is_high_value: 1, high_value_threshold: 1500.00, high_value_reason: 'Amount ($3,450.00) exceeds department threshold of $1,500.00', business_justification: 'Mission critical inbound lead capture and lifecycle email automation tool.', submission_date: '2026-09-20 14:20:00', approved_at: null, reimbursed_at: null, item_count: 1 },
  { claim_id: 4, claim_number: 'EXP-2026-004', employee_id: 12, employee_name: 'Sophia Taylor', employee_code: 'EMP104', employee_email: 'sophia.taylor@company.com', department_id: 3, department_name: 'Sales & Enterprise Accounts', department_code: 'SLS', budget_id: 3, title: 'Fortune 500 Enterprise Pitch - NYC Travel & Client Dinner', total_amount: 1850.00, currency: 'USD', status: 'PENDING_MANAGER', is_high_value: 1, high_value_threshold: 1200.00, high_value_reason: 'Amount ($1,850.00) exceeds department threshold of $1,200.00', business_justification: 'Closed-door meeting with client procurement VP. Led to $180k ARR contract draft.', submission_date: '2026-09-22 09:00:00', approved_at: null, reimbursed_at: null, item_count: 3 },
  { claim_id: 5, claim_number: 'EXP-2026-005', employee_id: 13, employee_name: 'Jordan Lee', employee_code: 'EMP105', employee_email: 'jordan.lee@company.com', department_id: 4, department_name: 'People & Talent Operations', department_code: 'HR', budget_id: 4, title: 'Annual Company Team Wellness Day Catering & Materials', total_amount: 950.00, currency: 'USD', status: 'PENDING_MANAGER', is_high_value: 1, high_value_threshold: 800.00, high_value_reason: 'Amount ($950.00) exceeds department threshold of $800.00', business_justification: 'Quarterly team wellness day for 50 attendees including healthy catering and mindfulness coaches.', submission_date: '2026-09-18 16:45:00', approved_at: null, reimbursed_at: null, item_count: 2 },
  { claim_id: 6, claim_number: 'EXP-2026-006', employee_id: 14, employee_name: 'Aiden Walker', employee_code: 'EMP106', employee_email: 'aiden.walker@company.com', department_id: 6, department_name: 'Customer Operations & Support', department_code: 'OPS', budget_id: 6, title: 'Noise Cancelling Call Center Headsets (x5)', total_amount: 750.00, currency: 'USD', status: 'APPROVED', is_high_value: 0, high_value_threshold: 1000.00, high_value_reason: null, business_justification: 'Replacement gear for tier-2 frontline customer support engineers.', submission_date: '2026-08-25 13:10:00', approved_at: '2026-08-26 10:00:00', reimbursed_at: '2026-08-28 17:00:00', item_count: 1 },
  { claim_id: 7, claim_number: 'EXP-2026-007', employee_id: 12, employee_name: 'Sophia Taylor', employee_code: 'EMP104', employee_email: 'sophia.taylor@company.com', department_id: 3, department_name: 'Sales & Enterprise Accounts', department_code: 'SLS', budget_id: 3, title: 'VIP Luxury Club Dinner with Prospects', total_amount: 1450.00, currency: 'USD', status: 'REJECTED', is_high_value: 1, high_value_threshold: 1200.00, high_value_reason: 'Amount exceeds policy limit without pre-authorization', business_justification: 'Dinner with 2 prospective partners at 5-star venue.', submission_date: '2026-08-14 20:00:00', approved_at: null, reimbursed_at: null, item_count: 1 },
  { claim_id: 8, claim_number: 'EXP-2026-008', employee_id: 9, employee_name: 'Liam Vance', employee_code: 'EMP101', employee_email: 'liam.vance@company.com', department_id: 1, department_name: 'Engineering & Product', department_code: 'ENG', budget_id: 1, title: 'KubeCon North America 2026 Flight & Ticket', total_amount: 2600.00, currency: 'USD', status: 'PENDING_MANAGER', is_high_value: 1, high_value_threshold: 2500.00, high_value_reason: 'Amount ($2,600.00) exceeds department threshold of $2,500.00', business_justification: 'Speaking engagement at KubeCon on distributed systems architecture representing company.', submission_date: '2026-09-24 15:30:00', approved_at: null, reimbursed_at: null, item_count: 2 }
];

export const initialItems = [
  { item_id: 1, claim_id: 1, category_id: 5, category_name: 'Cloud & SaaS Subscriptions', category_code: 'IT-CLD', item_date: '2026-08-01', merchant_name: 'Amazon Web Services Inc.', amount: 4500.00, tax_amount: 350.00, receipt_url: 'https://storage.company.com/receipts/aws_invoice_8829.pdf', receipt_filename: 'aws_invoice_8829.pdf', notes: 'Reserved instance compute charges' },
  { item_id: 2, claim_id: 2, category_id: 6, category_name: 'Hardware & Workstation Gear', category_code: 'IT-EQP', item_date: '2026-08-09', merchant_name: 'Dell Technologies Direct', amount: 650.00, tax_amount: 52.00, receipt_url: 'https://storage.company.com/receipts/dell_inv_441.pdf', receipt_filename: 'dell_inv_441.pdf', notes: 'UltraSharp 27-inch 4K Monitor' },
  { item_id: 3, claim_id: 2, category_id: 6, category_name: 'Hardware & Workstation Gear', category_code: 'IT-EQP', item_date: '2026-08-09', merchant_name: 'Anker Direct', amount: 138.00, tax_amount: 0.00, receipt_url: 'https://storage.company.com/receipts/anker_hub_99.pdf', receipt_filename: 'anker_hub_99.pdf', notes: 'Thunderbolt 4 Docking Station' },
  { item_id: 4, claim_id: 3, category_id: 5, category_name: 'Cloud & SaaS Subscriptions', category_code: 'IT-CLD', item_date: '2026-09-19', merchant_name: 'HubSpot Inc.', amount: 3200.00, tax_amount: 250.00, receipt_url: 'https://storage.company.com/receipts/hubspot_ann_2026.pdf', receipt_filename: 'hubspot_ann_2026.pdf', notes: 'Annual subscription license for marketing automation' },
  { item_id: 5, claim_id: 4, category_id: 1, category_name: 'Airfare & Flights', category_code: 'TRV-AIR', item_date: '2026-09-21', merchant_name: 'Delta Air Lines', amount: 780.00, tax_amount: 62.40, receipt_url: 'https://storage.company.com/receipts/delta_flight_nyc.pdf', receipt_filename: 'delta_flight_nyc.pdf', notes: 'Roundtrip SFO to JFK Economy Plus' },
  { item_id: 6, claim_id: 4, category_id: 2, category_name: 'Lodging & Hotels', category_code: 'TRV-LOD', item_date: '2026-09-21', merchant_name: 'Marriott Downtown NYC', amount: 680.00, tax_amount: 95.20, receipt_url: 'https://storage.company.com/receipts/marriott_nyc_2nights.pdf', receipt_filename: 'marriott_nyc_2nights.pdf', notes: '2 nights business lodging' },
  { item_id: 7, claim_id: 4, category_id: 4, category_name: 'Client Meals & Entertainment', category_code: 'MEL-ENT', item_date: '2026-09-22', merchant_name: 'Gramercy Tavern NYC', amount: 390.00, tax_amount: 34.00, receipt_url: 'https://storage.company.com/receipts/gramercy_dinner.pdf', receipt_filename: 'gramercy_dinner.pdf', notes: 'Working dinner with 3 client stakeholders' },
  { item_id: 8, claim_id: 5, category_id: 8, category_name: 'Office Supplies & Logistics', category_code: 'OFC-SPL', item_date: '2026-09-18', merchant_name: 'Whole Foods Corporate Catering', amount: 620.00, tax_amount: 49.60, receipt_url: 'https://storage.company.com/receipts/wholefoods_catering.pdf', receipt_filename: 'wholefoods_catering.pdf', notes: 'Organic lunch buffet for 50 employees' },
  { item_id: 9, claim_id: 5, category_id: 7, category_name: 'Conferences & Certifications', category_code: 'EDU-CNF', item_date: '2026-09-18', merchant_name: 'MindfulWorks Workshop Co.', amount: 330.00, tax_amount: 0.00, receipt_url: 'https://storage.company.com/receipts/mindfulworks_invoice.pdf', receipt_filename: 'mindfulworks_invoice.pdf', notes: 'Certified wellness instructor fee' },
  { item_id: 10, claim_id: 6, category_id: 6, category_name: 'Hardware & Workstation Gear', category_code: 'IT-EQP', item_date: '2026-08-24', merchant_name: 'Jabra Business Solutions', amount: 750.00, tax_amount: 60.00, receipt_url: 'https://storage.company.com/receipts/jabra_biz_5x.pdf', receipt_filename: 'jabra_biz_5x.pdf', notes: '5x Jabra Evolve2 65 Headsets' },
  { item_id: 11, claim_id: 7, category_id: 4, category_name: 'Client Meals & Entertainment', category_code: 'MEL-ENT', item_date: '2026-08-13', merchant_name: 'Le Bernardin Luxury Dining', amount: 1450.00, tax_amount: 130.50, receipt_url: 'https://storage.company.com/receipts/lebernardin_rec.pdf', receipt_filename: 'lebernardin_rec.pdf', notes: 'Non-compliant expense exceeding reasonable policy thresholds' },
  { item_id: 12, claim_id: 8, category_id: 1, category_name: 'Airfare & Flights', category_code: 'TRV-AIR', item_date: '2026-09-24', merchant_name: 'United Airlines', amount: 1250.00, tax_amount: 100.00, receipt_url: 'https://storage.company.com/receipts/united_kubecon_flight.pdf', receipt_filename: 'united_kubecon_flight.pdf', notes: 'Direct flight to Chicago' },
  { item_id: 13, claim_id: 8, category_id: 7, category_name: 'Conferences & Certifications', category_code: 'EDU-CNF', item_date: '2026-09-24', merchant_name: 'Linux Foundation Events', amount: 1350.00, tax_amount: 0.00, receipt_url: 'https://storage.company.com/receipts/kubecon_pass_2026.pdf', receipt_filename: 'kubecon_pass_2026.pdf', notes: 'Conference full-access attendee pass' }
];

export const initialWorkflows = [
  { workflow_id: 1, claim_id: 1, step_order: 1, approver_id: 4, approver_name: 'Alex Chen', approver_role: 'DEPARTMENT_HEAD', status: 'APPROVED', comments: 'Approved critical infrastructure reservation.', deadline_at: '2026-08-03 10:30:00', action_taken_at: '2026-08-02 09:15:00', is_escalated: 0 },
  { workflow_id: 2, claim_id: 1, step_order: 2, approver_id: 1, approver_name: 'Sarah Jenkins', approver_role: 'CFO', status: 'APPROVED', comments: 'Approved high-value cloud procurement.', deadline_at: '2026-08-05 14:00:00', action_taken_at: '2026-08-03 14:00:00', is_escalated: 0 },
  { workflow_id: 3, claim_id: 3, step_order: 1, approver_id: 5, approver_name: 'Elena Rostova', approver_role: 'MANAGER', status: 'APPROVED', comments: 'Essential for Q4 lead generation campaign.', deadline_at: '2026-09-22 14:20:00', action_taken_at: '2026-09-21 11:00:00', is_escalated: 0 },
  { workflow_id: 4, claim_id: 3, step_order: 2, approver_id: 1, approver_name: 'Sarah Jenkins', approver_role: 'CFO', status: 'PENDING', comments: null, deadline_at: '2026-09-27 11:00:00', action_taken_at: null, is_escalated: 0 },
  { workflow_id: 5, claim_id: 4, step_order: 1, approver_id: 6, approver_name: 'Marcus Brody', approver_role: 'MANAGER', status: 'PENDING', comments: null, deadline_at: '2026-09-24 09:00:00', action_taken_at: null, is_escalated: 1 },
  { workflow_id: 6, claim_id: 5, step_order: 1, approver_id: 7, approver_name: 'Rachel Green', approver_role: 'MANAGER', status: 'PENDING', comments: null, deadline_at: '2026-09-20 16:45:00', action_taken_at: null, is_escalated: 1 },
  { workflow_id: 7, claim_id: 8, step_order: 1, approver_id: 4, approver_name: 'Alex Chen', approver_role: 'DEPARTMENT_HEAD', status: 'PENDING', comments: null, deadline_at: '2026-09-26 15:30:00', action_taken_at: null, is_escalated: 0 }
];

export const initialLedger = [
  { ledger_id: 1, budget_id: 1, claim_id: 1, transaction_type: 'ENCUMBRANCE', amount: 4850.00, balance_after: 115150.00, description: 'Encumbrance hold for Claim EXP-2026-001', recorded_by: 9, recorded_by_name: 'Liam Vance', claim_number: 'EXP-2026-001', created_at: '2026-08-01 10:30:00' },
  { ledger_id: 2, budget_id: 1, claim_id: 1, transaction_type: 'SETTLEMENT', amount: 4850.00, balance_after: 65800.00, description: 'Settlement for approved Claim EXP-2026-001', recorded_by: 1, recorded_by_name: 'Sarah Jenkins', claim_number: 'EXP-2026-001', created_at: '2026-08-03 14:00:00' },
  { ledger_id: 3, budget_id: 2, claim_id: 3, transaction_type: 'ENCUMBRANCE', amount: 3450.00, balance_after: 9600.00, description: 'Encumbrance hold for Claim EXP-2026-003', recorded_by: 11, recorded_by_name: 'Noah Patel', claim_number: 'EXP-2026-003', created_at: '2026-09-20 14:20:00' },
  { ledger_id: 4, budget_id: 3, claim_id: 4, transaction_type: 'ENCUMBRANCE', amount: 1850.00, balance_after: 1900.00, description: 'Encumbrance hold for Claim EXP-2026-004', recorded_by: 12, recorded_by_name: 'Sophia Taylor', claim_number: 'EXP-2026-004', created_at: '2026-09-22 09:00:00' },
  { ledger_id: 5, budget_id: 1, claim_id: 8, transaction_type: 'ENCUMBRANCE', amount: 2600.00, balance_after: 57500.00, description: 'Encumbrance hold for Claim EXP-2026-008', recorded_by: 9, recorded_by_name: 'Liam Vance', claim_number: 'EXP-2026-008', created_at: '2026-09-24 15:30:00' }
];

export const initialAuditLogs = [
  { log_id: 1, entity_name: 'expense_claims', entity_id: 1, action: 'SUBMITTED', performed_by: 9, performed_by_name: 'Liam Vance', role: 'EMPLOYEE', created_at: '2026-08-01 10:30:00', details: 'Claim EXP-2026-001 submitted ($4,850.00)' },
  { log_id: 2, entity_name: 'expense_claims', entity_id: 1, action: 'APPROVED_MANAGER', performed_by: 4, performed_by_name: 'Alex Chen', role: 'DEPARTMENT_HEAD', created_at: '2026-08-02 09:15:00', details: 'Step 1 Manager sign-off completed' },
  { log_id: 3, entity_name: 'expense_claims', entity_id: 1, action: 'APPROVED_FINAL', performed_by: 1, performed_by_name: 'Sarah Jenkins', role: 'CFO', created_at: '2026-08-03 14:00:00', details: 'Step 2 CFO approval and budget settlement completed' },
  { log_id: 4, entity_name: 'expense_claims', entity_id: 7, action: 'REJECTED', performed_by: 6, performed_by_name: 'Marcus Brody', role: 'MANAGER', created_at: '2026-08-15 10:00:00', details: 'Claim EXP-2026-007 rejected; encumbered funds released' },
  { log_id: 5, entity_name: 'expense_claims', entity_id: 8, action: 'SUBMITTED', performed_by: 9, performed_by_name: 'Liam Vance', role: 'EMPLOYEE', created_at: '2026-09-24 15:30:00', details: 'Claim EXP-2026-008 submitted ($2,600.00) - High-Value flag triggered' }
];

export const initialFraudDetections = [
  { type: 'POLICY_OVERRUN_RISK', severity: 'HIGH', claim_number: 'EXP-2026-004', employee: 'Sophia Taylor', amount: 1850.00, description: 'Sales department budget is at 96.8% utilization. Approving this claim leaves under $50 headroom for Q3.' },
  { type: 'THRESHOLD_BYPASS_SPLIT', severity: 'MEDIUM', claim_number: 'EXP-2026-002', employee: 'Chloe Zhao', amount: 840.00, description: 'Multiple tech peripheral purchases submitted within short intervals near approval thresholds.' },
  { type: 'SLA_BREACH_ALERT', severity: 'HIGH', claim_number: 'EXP-2026-005', employee: 'Jordan Lee', amount: 950.00, description: 'Pending approval SLA breached (> 5 days elapsed awaiting Rachel Green action).' }
];
